from __future__ import annotations

import io
import os
import secrets
from html import escape
from urllib.parse import urlencode

import qrcode
import streamlit as st

from game_engine import GameError, GameManager


st.set_page_config(
    page_title="RIFT — Multiplayer Escape Mission",
    page_icon="◈",
    layout="wide",
    initial_sidebar_state="collapsed",
)


def load_css() -> None:
    css_path = os.path.join(os.path.dirname(__file__), "assets", "styles.css")
    with open(css_path, "r", encoding="utf-8") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)


load_css()


@st.cache_resource
def get_manager() -> GameManager:
    return GameManager()


manager = get_manager()


def query_value(key: str) -> str:
    value = st.query_params.get(key, "")
    if isinstance(value, list):
        value = value[0] if value else ""
    return str(value).strip()


def init_session() -> None:
    # Keep a lightweight reconnect token in the URL. Invite links generated by the app
    # contain only the room code, so a player's private token is not shared with teammates.
    query_player = query_value("player")
    st.session_state.setdefault("player_id", query_player or secrets.token_urlsafe(10))
    st.session_state.setdefault("room_code", None)
    st.session_state.setdefault("player_name", "")
    st.session_state.setdefault("notice", None)
    st.session_state.setdefault("error", None)

    query_room = query_value("room").upper()[:4]
    if not st.session_state.room_code and query_room and query_player:
        if manager.reconnect(query_room, st.session_state.player_id):
            st.session_state.room_code = query_room
            try:
                snapshot = manager.get_snapshot(query_room, st.session_state.player_id)
                me = next((p for p in snapshot["players"] if p["id"] == st.session_state.player_id), None)
                if me:
                    st.session_state.player_name = me["name"]
            except GameError:
                st.session_state.room_code = None


init_session()


def show_messages() -> None:
    if st.session_state.get("notice"):
        st.success(st.session_state.pop("notice"))
    if st.session_state.get("error"):
        st.error(st.session_state.pop("error"))


def set_error(message: str) -> None:
    st.session_state.error = message


def set_notice(message: str) -> None:
    st.session_state.notice = message


def safe_run(action, success_message: str | None = None) -> bool:
    try:
        action()
        if success_message:
            set_notice(success_message)
        return True
    except GameError as exc:
        set_error(str(exc))
        return False


def home_page() -> None:
    st.markdown(
        """
        <div class="hero-shell">
          <div class="rift-kicker">COOPERATIVE // REAL-TIME // 2–6 PLAYERS</div>
          <div class="rift-logo">RIFT</div>
          <div class="rift-tagline">Every screen holds part of the truth.</div>
          <p class="rift-subtitle">
            A distributed multiplayer escape mission. Your crew receives different clues on different devices.
            Communicate, decode the system failures, and contain the RIFT before station integrity collapses.
          </p>
          <div class="metric-grid">
            <div class="metric-card"><div class="metric-label">Crew</div><div class="metric-value">2–6 players</div></div>
            <div class="metric-card"><div class="metric-label">Mission</div><div class="metric-value">~10 minutes</div></div>
            <div class="metric-card"><div class="metric-label">Install</div><div class="metric-value">None</div></div>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    show_messages()
    st.markdown('<div class="section-title">ENTER MISSION CONTROL</div>', unsafe_allow_html=True)

    create_col, join_col = st.columns(2, gap="large")

    with create_col:
        st.markdown(
            '<div class="terminal-card"><div class="terminal-label">START A NEW CREW</div><h3>Create Mission</h3><p class="small-note">You become commander and receive a four-character room code to share.</p></div>',
            unsafe_allow_html=True,
        )
        with st.form("create_room_form"):
            create_name = st.text_input("Your callsign", max_chars=20, placeholder="e.g. Nova")
            create_submit = st.form_submit_button("Create mission", use_container_width=True)
        if create_submit:
            def do_create():
                code = manager.create_room(st.session_state.player_id, create_name)
                st.session_state.room_code = code
                st.session_state.player_name = create_name.strip()
                st.query_params["room"] = code
                st.query_params["player"] = st.session_state.player_id
            if safe_run(do_create):
                st.rerun()

    with join_col:
        st.markdown(
            '<div class="terminal-card"><div class="terminal-label">JOIN AN EXISTING CREW</div><h3>Join Mission</h3><p class="small-note">Enter the room code your commander shared. No account required.</p></div>',
            unsafe_allow_html=True,
        )
        query_code = st.query_params.get("room", "")
        if isinstance(query_code, list):
            query_code = query_code[0] if query_code else ""
        with st.form("join_room_form"):
            join_name = st.text_input("Your callsign", max_chars=20, placeholder="e.g. Atlas", key="join_name")
            join_code = st.text_input("Room code", value=str(query_code).upper()[:4], max_chars=4, placeholder="X7K9", key="join_code")
            join_submit = st.form_submit_button("Join crew", use_container_width=True)
        if join_submit:
            def do_join():
                manager.join_room(join_code, st.session_state.player_id, join_name)
                st.session_state.room_code = join_code.upper().strip()
                st.session_state.player_name = join_name.strip()
                st.query_params["room"] = st.session_state.room_code
                st.query_params["player"] = st.session_state.player_id
            if safe_run(do_join):
                st.rerun()

    st.markdown('<div class="divider"></div>', unsafe_allow_html=True)
    st.markdown('<div class="section-title">HOW THE MISSION WORKS</div>', unsafe_allow_html=True)
    rules = [
        ("01", "Different screens", "Each operator receives information the others cannot see."),
        ("02", "Communicate", "Talk out loud or use Team Comms to combine your clues."),
        ("03", "Transmit", "Work out the shared authorization code and send it before time expires."),
        ("04", "Protect integrity", "Incorrect transmissions damage the station. Reach zero and the mission ends."),
    ]
    cols = st.columns(4)
    for col, (num, title, copy) in zip(cols, rules):
        with col:
            st.markdown(
                f'<div class="rule-card"><div class="rule-number">{num}</div><div class="rule-title">{title}</div><div class="rule-copy">{copy}</div></div>',
                unsafe_allow_html=True,
            )


def qr_image_for_room(code: str) -> bytes | None:
    public_url = os.getenv("PUBLIC_URL", "").strip()
    if not public_url:
        try:
            public_url = str(st.secrets.get("PUBLIC_URL", "")).strip()
        except Exception:
            public_url = ""
    public_url = public_url.rstrip("/")
    if not public_url:
        return None
    url = f"{public_url}/?{urlencode({'room': code})}"
    img = qrcode.make(url)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def render_players(snapshot: dict, viewer_id: str) -> None:
    for p in snapshot["players"]:
        host = p["id"] == snapshot["host_player_id"]
        you = p["id"] == viewer_id
        label = f"{escape(p['name'])}{' · YOU' if you else ''}"
        role = "COMMANDER" if host and snapshot["state"] == "LOBBY" else escape(p.get("role") or "CREW")
        dot_class = "dot" if p.get("connected", True) else "dot offline"
        st.markdown(
            f"""
            <div class="player-row">
              <div class="player-main"><span class="{dot_class}"></span><span class="player-name">{label}</span></div>
              <span class="role-chip">{role}</span>
            </div>
            """,
            unsafe_allow_html=True,
        )


def render_top_metrics(snapshot: dict) -> None:
    mission_no = snapshot["mission"]["number"] if snapshot.get("mission") else max(0, snapshot["mission_index"] + 1)
    integrity = snapshot["integrity"]
    bar_class = "integrity-fill danger" if integrity <= 35 else "integrity-fill"
    st.markdown(
        f"""
        <div class="metric-grid">
          <div class="metric-card"><div class="metric-label">Mission</div><div class="metric-value">{mission_no}/5</div></div>
          <div class="metric-card"><div class="metric-label">Crew Score</div><div class="metric-value">{snapshot['score']:,}</div></div>
          <div class="metric-card"><div class="metric-label">Station Integrity</div><div class="metric-value">{integrity}%</div><div class="integrity-bar"><div class="{bar_class}" style="width:{integrity}%"></div></div></div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_chat(snapshot: dict, code: str, player_id: str) -> None:
    st.markdown('<div class="section-title">TEAM COMMS</div>', unsafe_allow_html=True)
    if not snapshot["chat"]:
        st.markdown('<div class="small-note">No transmissions yet. Share only what your terminal shows you.</div>', unsafe_allow_html=True)
    else:
        for msg in snapshot["chat"][-8:]:
            st.markdown(
                f'<div class="chat-message"><div class="chat-name">{escape(msg["player_name"])}</div><div class="chat-text">{escape(msg["text"])}</div></div>',
                unsafe_allow_html=True,
            )
    with st.form(f"chat_form_{code}", clear_on_submit=True):
        chat_text = st.text_input("Transmission", max_chars=180, label_visibility="collapsed", placeholder="Send a short message to the crew…")
        send = st.form_submit_button("Transmit", use_container_width=True)
    if send and chat_text.strip():
        safe_run(lambda: manager.add_chat(code, player_id, chat_text))


def render_lobby(snapshot: dict, code: str, player_id: str) -> None:
    is_host = player_id == snapshot["host_player_id"]
    left, right = st.columns([1.35, 1], gap="large")
    with left:
        st.markdown('<div class="rift-kicker">MISSION LOBBY // ORION-7</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="room-code">{escape(code)}</div>', unsafe_allow_html=True)
        st.markdown('<div class="room-caption">Share this code with your crew. Every operator joins from their own device.</div>', unsafe_allow_html=True)
        qr = qr_image_for_room(code)
        if qr:
            st.image(qr, width=170, caption="Scan to join this room")
        else:
            st.markdown('<div class="small-note">QR join activates automatically after the public deployment URL is configured.</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-title">CREW STATUS</div>', unsafe_allow_html=True)
        render_players(snapshot, player_id)

    with right:
        st.markdown('<div class="terminal-card"><div class="terminal-label">MISSION READINESS</div><h3>Distributed Control Protocol</h3><p class="small-note">Every screen will reveal different evidence. Your crew must communicate to reconstruct each authorization code.</p></div>', unsafe_allow_html=True)
        st.metric("Operators connected", f"{len(snapshot['players'])} / 6")
        if len(snapshot["players"]) < 2:
            st.info("Waiting for at least one more operator.")
        elif is_host:
            if st.button("Begin mission briefing", type="primary", use_container_width=True):
                if safe_run(lambda: manager.start_game(code, player_id)):
                    st.rerun()
        else:
            st.info("Crew ready. Waiting for the commander to begin.")
        if st.button("Leave room", use_container_width=True):
            manager.leave_room(code, player_id)
            st.session_state.room_code = None
            st.query_params.clear()
            st.rerun()


def render_briefing(snapshot: dict, code: str, player_id: str) -> None:
    is_host = player_id == snapshot["host_player_id"]
    st.markdown('<div class="rift-kicker">ORION-7 // CRITICAL SYSTEM FAILURE</div>', unsafe_allow_html=True)
    st.markdown('<div class="mission-title">Your terminal is not the whole truth.</div>', unsafe_allow_html=True)
    st.markdown(
        '<p class="rift-subtitle">Five systems are failing. Each operator sees a different fragment of the recovery protocol. Read your clues exactly, communicate with the crew, and transmit the shared code before the clock expires.</p>',
        unsafe_allow_html=True,
    )
    render_top_metrics(snapshot)

    cols = st.columns(3)
    cards = [
        ("01", "Read your terminal", "Never assume another operator can see your clue."),
        ("02", "Combine evidence", "Sequence + mapping + transformation rules form the solution."),
        ("03", "Protect the station", "Wrong codes damage integrity; expired timers also cost integrity."),
    ]
    for c, item in zip(cols, cards):
        with c:
            st.markdown(f'<div class="rule-card"><div class="rule-number">{item[0]}</div><div class="rule-title">{item[1]}</div><div class="rule-copy">{item[2]}</div></div>', unsafe_allow_html=True)

    st.markdown('<div class="section-title">CURRENT ROLE ASSIGNMENTS</div>', unsafe_allow_html=True)
    render_players(snapshot, player_id)
    launch_label = "Launch recovery step 1" if is_host else "Crew ready — launch recovery step 1"
    if st.button(launch_label, type="primary", use_container_width=True):
        if safe_run(lambda: manager.launch_next_mission(code, player_id)):
            st.rerun()
    if not is_host:
        st.caption("Any active operator may continue the mission if the commander disconnects.")


def render_active(snapshot: dict, code: str, player_id: str) -> None:
    mission = snapshot["mission"]
    remaining = mission["remaining_seconds"]
    mm, ss = divmod(max(0, remaining), 60)
    timer_class = "timer-value timer-danger" if remaining <= 20 else "timer-value"

    render_top_metrics(snapshot)
    st.markdown(
        f"""
        <div class="mission-header">
          <div class="mission-number">RECOVERY STEP {mission['number']:02d} // {escape(mission['template'])}</div>
          <div class="mission-title">{escape(mission['title'])}</div>
          <div class="mission-subtitle">{escape(mission['subtitle'])}</div>
        </div>
        <div class="timer-wrap"><div class="terminal-label">RECOVERY WINDOW</div><div class="{timer_class}">{mm:02d}:{ss:02d}</div></div>
        """,
        unsafe_allow_html=True,
    )

    clue_col, action_col = st.columns([1.35, 1], gap="large")
    with clue_col:
        st.markdown('<div class="section-title">YOUR PRIVATE TERMINAL</div>', unsafe_allow_html=True)
        for i, clue in enumerate(mission["viewer_clues"], start=1):
            op = " operator" if "PRIMARY CONTROL" in clue else ""
            st.markdown(
                f'<div class="clue-card{op}"><div class="clue-index">DATA PACKET {i:02d}</div><div class="clue-text">{escape(clue)}</div></div>',
                unsafe_allow_html=True,
            )
        st.markdown('<div class="small-note">Other operators have different packets. Do not refresh expecting to reveal theirs—the clue split is intentional.</div>', unsafe_allow_html=True)

    with action_col:
        designated = player_id == mission["operator_player_id"]
        badge = "PRIMARY OPERATOR" if designated else "BACKUP TRANSMITTER"
        st.markdown(
            f'<div class="terminal-card"><div class="terminal-label">{badge}</div><h3>Authorization Console</h3><p class="small-note">Enter only the final numeric authorization code your crew agrees on.</p></div>',
            unsafe_allow_html=True,
        )
        with st.form(f"solution_{code}_{mission['number']}", clear_on_submit=True):
            answer = st.text_input("Authorization code", max_chars=8, placeholder="••••", help="Letters/spaces are ignored; most recovery codes are 4–5 digits.")
            transmit = st.form_submit_button("Transmit override", type="primary", use_container_width=True)
        if transmit:
            try:
                result = manager.submit_solution(code, player_id, answer)
                if result["correct"]:
                    set_notice(f"Override accepted. +{result['points']:,} crew points.")
                else:
                    set_error(f"Override rejected. Station integrity −{result['damage']}%.")
                st.rerun()
            except GameError as exc:
                set_error(str(exc))
                st.rerun()
        st.markdown(f'<div class="small-note">Attempts this step: <span class="mono">{mission["attempts"]}</span></div>', unsafe_allow_html=True)
        render_chat(snapshot, code, player_id)


def render_result(snapshot: dict, code: str, player_id: str) -> None:
    mission = snapshot["mission"]
    is_host = player_id == snapshot["host_player_id"]
    render_top_metrics(snapshot)
    success = mission["status"] == "SUCCESS"
    banner_class = "success-banner" if success else "failure-banner"
    title = "SYSTEM RESTORED" if success else "RECOVERY STEP FAILED"
    subtitle = (
        f"Authorization confirmed · +{mission['points_awarded']:,} crew points"
        if success
        else escape(mission.get("failure_reason") or "The system rejected the recovery window.")
    )
    st.markdown(
        f'<div class="{banner_class}"><div class="banner-title">{title}</div><div class="banner-sub">{subtitle}</div></div>',
        unsafe_allow_html=True,
    )
    st.markdown(f'<div class="mission-title">{escape(mission["title"])}</div>', unsafe_allow_html=True)
    st.markdown(
        f'<div class="terminal-card"><div class="terminal-label">CONFIRMED AUTHORIZATION</div><div class="room-code" style="font-size:2.3rem">{escape(mission["solution"] or "—")}</div><div class="small-note">Crew attempts: {mission["attempts"]}</div></div>',
        unsafe_allow_html=True,
    )
    st.markdown('<div class="section-title">CREW</div>', unsafe_allow_html=True)
    render_players(snapshot, player_id)

    label = "Seal mission report" if mission["number"] >= 5 else f"Launch recovery step {mission['number'] + 1}"
    if st.button(label, type="primary", use_container_width=True):
        if safe_run(lambda: manager.launch_next_mission(code, player_id)):
            st.rerun()
    if not is_host:
        st.caption("Any active operator may continue if the commander is unavailable.")
    render_chat(snapshot, code, player_id)


def render_complete(snapshot: dict, code: str, player_id: str) -> None:
    is_host = player_id == snapshot["host_player_id"]
    failed = snapshot["integrity"] <= 0
    status = "MISSION FAILED" if failed else "RIFT CONTAINED"
    kicker = "ORION-7 LOST" if failed else "SYSTEM RESTORED // CREW SYNCHRONIZED"
    st.markdown(f'<div class="rift-kicker">{kicker}</div>', unsafe_allow_html=True)
    st.markdown(f'<div class="rift-logo" style="font-size:clamp(2.8rem,8vw,6rem)">{status}</div>', unsafe_allow_html=True)
    st.markdown(
        '<p class="rift-subtitle">Your final score is shared across the entire crew. The mission only succeeds when the team combines what no single screen can reveal.</p>',
        unsafe_allow_html=True,
    )
    render_top_metrics(snapshot)

    successes = sum(1 for x in snapshot["mission_history"] if x["status"] == "SUCCESS")
    attempts = sum(x["attempts"] for x in snapshot["mission_history"])
    st.markdown(
        f"""
        <div class="metric-grid">
          <div class="metric-card"><div class="metric-label">Systems Restored</div><div class="metric-value">{successes}/5</div></div>
          <div class="metric-card"><div class="metric-label">Total Transmissions</div><div class="metric-value">{attempts}</div></div>
          <div class="metric-card"><div class="metric-label">Crew</div><div class="metric-value">{len(snapshot['players'])} operators</div></div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.markdown('<div class="section-title">FINAL CREW ROSTER</div>', unsafe_allow_html=True)
    render_players(snapshot, player_id)

    replay_label = "Run another mission" if is_host else "Reset room for another mission"
    if st.button(replay_label, type="primary", use_container_width=True):
        if safe_run(lambda: manager.play_again(code, player_id)):
            st.rerun()

    if st.button("Exit to mission control", use_container_width=True):
        manager.leave_room(code, player_id)
        st.session_state.room_code = None
        st.query_params.clear()
        st.rerun()


@st.fragment(run_every="1s")
def room_surface() -> None:
    code = st.session_state.get("room_code")
    player_id = st.session_state.player_id
    if not code:
        return
    try:
        manager.reconnect(code, player_id)
        snapshot = manager.get_snapshot(code, player_id)
    except GameError:
        st.session_state.room_code = None
        set_error("That mission room is no longer active.")
        st.rerun()
        return

    show_messages()
    state = snapshot["state"]
    if state == "LOBBY":
        render_lobby(snapshot, code, player_id)
    elif state == "BRIEFING":
        render_briefing(snapshot, code, player_id)
    elif state == "ACTIVE":
        render_active(snapshot, code, player_id)
    elif state == "RESULT":
        render_result(snapshot, code, player_id)
    elif state == "COMPLETE":
        render_complete(snapshot, code, player_id)


if st.session_state.get("room_code"):
    room_surface()
else:
    home_page()
